import { Injectable, inject } from '@angular/core';
import { PagedResult, RegistrationKey } from '../../../models';
import { ApiClient } from '../../api/api-client.service';
import { ApiPage, ApiRegistrationKey } from '../../api/api-models';
import { PagedSource } from '../../shared/query-spec';
import { RegistrationKeyStatus } from '../../../shared/registration-key-status';
import { toRegistrationKey } from '../../auth/current-user.mapper';
import { TenantContextService } from '../../tenant/tenant-context.service';

type KeyRole = NonNullable<RegistrationKey['role']>;
const API_ROLE: Record<KeyRole, 'PARENT' | 'APPLICATION_ADMIN'> = { userAdmin: 'PARENT', applicationAdmin: 'APPLICATION_ADMIN' };
const API_STATUS: Record<RegistrationKeyStatus, string> = { active: 'Active', inactive: 'Inactive', expired: 'Expired', used: 'Used' };
const iso = (epochMs: number | undefined) => (epochMs ? new Date(epochMs).toISOString() : null);

/**
 * The organization's registration keys, through the API (`/registration-keys`).
 *
 * The API confines them to the caller's organization and derives each key's
 * status when it is read, so there is no stored status to sweep as keys expire
 * and no tenant filter to remember. The code a family types is generated by the
 * server (`RegistrationKey.code`); `id` is only how the screens address a key.
 */
@Injectable({ providedIn: 'root' })
export class RegistrationKeyAdminService {
  private readonly api = inject(ApiClient);
  private readonly tenantContext = inject(TenantContextService);

  listKeys(pageSize = 10, cursor?: string): Promise<PagedResult<RegistrationKey>> {
    return this.page({}, pageSize, cursor);
  }

  async countKeys(): Promise<number> {
    return (await this.raw({}, 1, 1)).totalCount;
  }

  /**
   * The Registration Keys table, newest first, optionally one status, one role,
   * and codes containing `search`; the API applies each, so they cover every
   * page. Paged on the server.
   */
  pagedSource(status?: RegistrationKeyStatus, role?: KeyRole, search?: string): PagedSource<RegistrationKey> {
    const filter: Record<string, string> = {};
    if (status) filter['status'] = API_STATUS[status];
    if (role) filter['role'] = API_ROLE[role];
    if (search?.trim()) filter['search'] = search.trim();
    return {
      fetchPage: (pageSize, cursor) => this.page(filter, pageSize, cursor),
      fetchCount: async () => (await this.raw(filter, 1, 1)).totalCount
    };
  }

  async countByRole(role: KeyRole): Promise<number> {
    return (await this.raw({ role: API_ROLE[role] }, 1, 1)).totalCount;
  }

  async countByStatus(status: RegistrationKeyStatus): Promise<number> {
    return (await this.raw({ status: API_STATUS[status] }, 1, 1)).totalCount;
  }

  /** A new key; the server generates its code and returns the key as stored. */
  async createKey(key: { role: KeyRole; expiresAt?: number; maxChildUses?: number }): Promise<RegistrationKey> {
    const created = await this.api.post<ApiRegistrationKey>('/registration-keys', {
      role: API_ROLE[key.role],
      expiresOn: iso(key.expiresAt),
      maxChildren: key.role === 'userAdmin' ? key.maxChildUses ?? null : null
    });
    return this.toKey(created);
  }

  /** Switch on or off, change the expiry or the allowance (never below the children already enrolled). */
  async updateKey(key: RegistrationKey): Promise<void> {
    await this.api.put(`/registration-keys/${key.id}`, {
      isActive: key.active,
      expiresOn: iso(key.expiresAt),
      maxChildren: key.role === 'userAdmin' ? key.maxChildUses ?? null : null
    });
  }

  /** Only a key nobody registered with; one that admitted accounts is refused (409): switch it off instead. */
  async deleteKey(keyId: string): Promise<void> {
    await this.api.delete(`/registration-keys/${keyId}`);
  }

  private toKey(key: ApiRegistrationKey): RegistrationKey {
    return toRegistrationKey(key, this.tenantContext.tenantId() ?? undefined);
  }

  private raw(filter: Record<string, string>, page: number, pageSize: number): Promise<ApiPage<ApiRegistrationKey>> {
    return this.api.get<ApiPage<ApiRegistrationKey>>('/registration-keys', { ...filter, page, pageSize: Math.min(pageSize, 100) });
  }

  // cursor = the next page number
  private async page(filter: Record<string, string>, pageSize: number, cursor?: string): Promise<PagedResult<RegistrationKey>> {
    const page = cursor ? Number(cursor) : 1;
    const result = await this.raw(filter, page, pageSize);
    return {
      items: result.items.map(key => this.toKey(key)),
      nextCursor: page * result.pageSize < result.totalCount ? String(page + 1) : undefined
    };
  }
}
